# mouseless starter profile
#
# tap caps lock for escape
# hold caps lock to access the mouse layer

# limit capture to the real keyboards on this machine
devices:
- "AT Translated Set 2 keyboard"
- "ITE Tech. Inc. ITE Device(8910) Keyboard"
- "Thomas Haukland Cheapino2"
- "Thomas Haukland Cheapino2 Keyboard"

baseMouseSpeed: 900.0
baseScrollSpeed: 20.0

mouseAccelerationTime: 175.0
mouseAccelerationCurve: 2.0
mouseDecelerationTime: 250.0
mouseDecelerationCurve: 3.0

layers:
- name: initial
  bindings:
    capslock: tap-hold esc; toggle-layer mouse; 200

- name: mouse
  passThrough: true
  bindings:
    esc: layer initial
    capslock: layer initial
    q: layer initial
    space: layer mouse
    r: reload-config
    l: move 1 0
    j: move -1 0
    k: move 0 1
    i: move 0 -1
    p: scroll up
    n: scroll down
    leftalt: speed 4.0
    e: speed 0.3
    f: button left
    d: button middle
    s: button right
